version: "3.8"

services:

  spring:
    build:
      context: ../apps/hellop
    expose:
      - "8080"
    networks:
      - app-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - spring
    networks:
      - app-net

networks:
  app-net:
    driver: bridge